services:
  guacamole-lite:
    build: .
    container_name: guacamole-lite
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOST=guacd
      - GUACD_PORT=4822
    depends_on:
      - guacd
    networks:
      - guacamole-network

  guacd:
    image: guacamole/guacd
    container_name: guacd
    ports:
      - "4822:4822"
    networks:
      - guacamole-network

networks:
  guacamole-network:
    driver: bridge
